app:
  message: hello
  item: item
  go-visit-message: https://cccp-education.github.io/
  clientApp:
    name: 'server'

  #  text_to_add="# google
  #app.mail.account.no-reply.host=smtp.gmail.com
  #app.mail.account.no-reply.port=587
  #
  ## google account test
  #app.mail.account.no-reply.email=tester@gmail.com
  #app.mail.account.no-reply.password=sxckqebcmaimwfvl"
  mailbox:
    no-reply:
      from: webapp-r2dbc-jwt@localhost
      name: no-reply
      base-url: http://127.0.0.1:8080
      password: password
      enabled: true
      host: localhost
      port: 587
      smpt-properties:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
      imaps-properties:
        debug: true
        imaps:
          auth: true
          starttls:
            enable: true


  mail:
    base-url: http://127.0.0.1:8080
    from: webapp-r2dbc-jwt@localhost
    password: password
    enabled: true
    host: localhost
    port: 587
    property:
      debug: true
      transport:
        protocol: smtp
      smtp:
        auth: true
        starttls:
          enable: true
    token: 2e2a7d47-0476-4046-9c66-9f990f8d6d35-f840450f-e853-43a5-b3f4-bbc
  security:
    authentication:
      jwt:
        secret: secret
        base64-secret: MjNlZmQzMzgwM2MzN2FmMGNhZTY3NDllMDJiODg2YWRlMmY0ZDUzMzg2ODI4MTgxNmIxNzQ1OGEzMmNmNjY2OTA3Nzk4MzRkNDUzZWFlMTljZjJmNDU5NDNjOWI3NjRhNDg3MGYzODhiYjVjZWU5MmNhMDA2MDU3ZjA2NjJhODE=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000

  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800

#  encrypter:
#    secret: RGPD
#    salt: 33a9ef2640cb9830

spring:
  profiles:
    default: dev
  application:
    name: server
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/dev?currentSchema=dev
    username: dev
    password: secret
  devtools:
    restart:
      enabled: true
  thymeleaf:
    mode: HTML
  messages:
    basename: i18n/messages
    encoding: UTF-8
  webflux:
    problemdetails:
      enabled: true
  web:
    locale: fr_FR

springdoc:
  api-docs:
    enabled: false

logging:
  level:
    org:
      springframework:
        r2dbc: INFO
        org.hibernate.SQL: INFO

server:
  port: 8880

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: smollm:135m
    streaming-chat-model:
      base-url: http://localhost:11434
      model-name: smollm:135m