app:
  message: hello
  item: item
  go-visit-message: https://cccp-education.github.io/
  clientApp:
    name: 'server'
  mail:
    base-url: http://127.0.0.1:8080
    from: webapp-r2dbc-jwt@localhost
    password: password
    enabled: true
    host: localhost
    port: 587
    property:
      debug: true
      transport:
        protocol: smtp
      smtp:
        auth: true
        starttls:
          enable: true
    token: 2e2a7d47-0476-4046-9c66-9f990f8d6d35-f840450f-e853-43a5-b3f4-bbc

  security:
    authentication:
      jwt:
        secret: secret
        base64-secret: MjNlZmQzMzgwM2MzN2FmMGNhZTY3NDllMDJiODg2YWRlMmY0ZDUzMzg2ODI4MTgxNmIxNzQ1OGEzMmNmNjY2OTA3Nzk4MzRkNDUzZWFlMTljZjJmNDU5NDNjOWI3NjRhNDg3MGYzODhiYjVjZWU5MmNhMDA2MDU3ZjA2NjJhODE=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800

langchain4j:
  ollama:
    chat-model:
      model-name: llama3.2:3b-instruct-q8_0
      base-url: http://localhost:11434
      temperature: 0.7
      timeout: PT60S
      log-requests: true
      log-responses: true
    streaming-chat-model:
      model-name: llama3.2:3b-instruct-q8_0
      base-url: http://localhost:11434
      temperature: 0.7
      timeout: PT60S
      log-requests: true
      log-responses: true

spring:
  profiles:
    default: dev
  application:
    name: server
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/dev?currentSchema=dev
    username: dev
    password: secret
  devtools:
    restart:
      enabled: true
  thymeleaf:
    mode: HTML
  messages:
    basename: i18n/messages
    encoding: UTF-8
  webflux:
    problemdetails:
      enabled: true
  web:
    locale: fr_FR

springdoc:
  api-docs:
    enabled: false

logging:
  level:
    org:
      springframework:
        r2dbc: INFO
        org.hibernate.SQL: INFO

server:
  port: 8880